version: '3.8'

services:
  server:
    image: ${DOCKER_REPOSITORY:-mekanayarla-server}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: mekanayarla-server
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://thefoodhero_system:thefoodhero-db-admin@thefoodhero-dbt.czqmmcmc613w.eu-north-1.rds.amazonaws.com/mekanayarla?schema=public
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - mekanayarla-network

  web:
    image: ${DOCKER_REPOSITORY:-mekanayarla-web}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: mekanayarla-web
    ports:
      - "90:80"
    depends_on:
      - server
    networks:
      - mekanayarla-network

networks:
  mekanayarla-network:
    driver: bridge
