version: "3.8"

services:
  server:
    image: ${SERVER_IMAGE}:${IMAGE_TAG}
    container_name: mekanayarla-server
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - mekanayarla_net

  web:
    image: ${WEB_IMAGE}:${IMAGE_TAG}
    container_name: mekanayarla-web
    restart: always
    depends_on:
      - server
    ports:
      - "90:80"
    networks:
      - mekanayarla_net

networks:
  mekanayarla_net:
    external: true
