name: Deploy App Service

on:
  workflow_call:
    inputs:
      SERVER_HOST:
        type: string
        required: true
      SERVER_USER:
        type: string
        required: true
      service_name:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      THEFOODHEROAPI_SECRET:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v3

      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.THEFOODHEROAPI_SECRET }}

      - name: 📤 Copy docker-compose.yml
        run: |
          ssh -o StrictHostKeyChecking=no ${{ inputs.SERVER_USER }}@${{ inputs.SERVER_HOST }} "mkdir -p /app/mekanayarla"
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ inputs.SERVER_USER }}@${{ inputs.SERVER_HOST }}:/app/mekanayarla/docker-compose.yml

      - name: 🚀 Deploy Service
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
          SERVICE: ${{ inputs.service_name }}
          TAG: ${{ inputs.version }}
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ inputs.SERVER_USER }}@${{ inputs.SERVER_HOST }} "DOCKER_USER='$DOCKER_USER' DOCKER_PASS='$DOCKER_PASS' SERVICE='$SERVICE' TAG='$TAG' bash -s" << 'EOF'
            set -e
            cd /app/mekanayarla

            DOCKER_REPOSITORY="$DOCKER_USER/mekanayarla-$SERVICE"
            IMAGE_TAG="$TAG"

            echo "🚀 Deploying $SERVICE"
            echo "📦 Image: $DOCKER_REPOSITORY:$IMAGE_TAG"

            echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

            echo "🌐 Ensuring network exists: mekanayarla_net"
            docker network inspect mekanayarla_net >/dev/null 2>&1 || docker network create mekanayarla_net

            echo "🧹 Pre-deploy cleanup for $SERVICE..."
            docker image rm -f "$DOCKER_REPOSITORY:$IMAGE_TAG" || true

            # Pull and Update
            DOCKER_REPOSITORY=$DOCKER_REPOSITORY IMAGE_TAG=$IMAGE_TAG docker compose pull "$SERVICE"
            DOCKER_REPOSITORY=$DOCKER_REPOSITORY IMAGE_TAG=$IMAGE_TAG docker compose up -d --force-recreate "$SERVICE"

            echo "🧹 Keeping last 2 images for $SERVICE..."
            docker images "$DOCKER_REPOSITORY" \
              --format "{{.ID}} {{.CreatedAt}}" | \
              sort -r | tail -n +3 | awk '{print $1}' | xargs -r docker rmi || true

            docker logout
          EOF